# Generated by Django 4.2.16 on 2026-02-02 15:39

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_banners/', validators=[users.models.user.validate_image_size]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='student_banners/', validators=[users.models.user.validate_image_size]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[users.models.user.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/', validators=[users.models.user.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[users.models.user.validate_image_size]),
        ),
    ]
