# Generated by Django 4.2.16 on 2026-02-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructorprofile_banner_studentprofile_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accessibility_requirements',
            field=models.TextField(blank=True, help_text='Health/Accessibility info for accommodations', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_personalization_consent',
            field=models.BooleanField(default=False, help_text='Consent for AI/Adaptive learning personalization'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text="User's country of residence", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_processing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exclude_from_advertising',
            field=models.BooleanField(default=True, help_text='No targeted advertising or profiling for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_privacy_enabled',
            field=models.BooleanField(default=True, help_text='Default privacy settings set to high (Privacy by Design)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_id',
            field=models.CharField(blank=True, help_text='Emirates ID or Passport Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Multi-Factor Authentication status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parental_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_MANAGER', 'Team Manager'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], max_length=50),
        ),
    ]
