# Generated by Django 4.2.16 on 2026-05-29 13:37

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_accessibility_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='qualification',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/qualification/', validators=[users.models.user.validate_document_size]),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/resume/', validators=[users.models.user.validate_document_size]),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/trade_license/', validators=[users.models.user.validate_document_size]),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='trainer_eid',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/eid/', validators=[users.models.user.validate_document_size]),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to='instructor_docs/vat/', validators=[users.models.user.validate_document_size]),
        ),
    ]
