# Generated by Django 4.2.16 on 2025-12-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_twitter_instructor_x_link_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, help_text='Estimated duration in weeks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.organization'),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=5, help_text='Hours per week'),
        ),
    ]
