# Generated by Django 4.2.16 on 2025-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_approved_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('training', 'Training'), ('accreditation', 'Accreditation')], default='accreditation', max_length=20),
        ),
    ]
