# Generated by Django 4.2.16 on 2025-12-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('accreditation', 'Accreditation')], default='accreditation', max_length=20, null=True),
        ),
    ]
