# Generated by Django 4.2.16 on 2026-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='job_opportunity',
            field=models.TextField(blank=True, help_text='Basic job opportunity info', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. $50k - $80k', max_length=100, null=True),
        ),
    ]
