# Generated by Django 4.2.16 on 2026-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_job_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location for offline sessions', max_length=255),
        ),
        migrations.AddField(
            model_name='livesession',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link for the video call (Online only)'),
        ),
    ]
