# Generated by Django 4.2.16 on 2026-02-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_assessment_presentation_assessmentquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='e.g. KHDA, ADEK, CAA, MOE', max_length=200)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('scope', models.TextField(blank=True, help_text='Scope of e-learning platforms authority')),
            ],
            options={
                'verbose_name_plural': 'Regulatory Authorities',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('regulation_type', models.CharField(choices=[('PDPL', 'UAE Data Protection Law'), ('CDSL', 'UAE Child Digital Safety Law'), ('ECC', 'E-Commerce Law'), ('KSA_PDPL', 'Saudi Personal Data Protection Law'), ('BAHRAIN_PDPL', 'Bahrain PDPL'), ('QATAR_PDPL', 'Qatar PDPL'), ('OMAN_PDPL', 'Oman PDPL'), ('KUWAIT_DPPR', 'Kuwait DPPR'), ('GCC_SPECIFIC', 'GCC Specific Regulation')], max_length=50)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('reference_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('source_name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='course',
            name='classification_tier',
            field=models.CharField(blank=True, help_text='National risk-based classification tier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_safety_checked',
            field=models.BooleanField(default=False, help_text='Proactively reviewed for harmful content'),
        ),
        migrations.AddField(
            model_name='course',
            name='data_residency_region',
            field=models.CharField(default='UAE', help_text='Region where learner data is hosted (e.g. UAE Region, Microsoft Azure UAE North)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='drm_enabled',
            field=models.BooleanField(default=False, help_text='Digital Rights Management for premium content'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_child_safe',
            field=models.BooleanField(default=False, help_text='Compliant with UAE Child Digital Safety Law'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_pdpl_compliant',
            field=models.BooleanField(default=True, help_text='Individual course compliance with UAE Data Protection Law'),
        ),
        migrations.AddField(
            model_name='course',
            name='license_required',
            field=models.CharField(blank=True, help_text='Specific license needed (e.g., KHDA App, Training & Consultancy)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='min_age_requirement',
            field=models.PositiveIntegerField(default=0, help_text='Minimum age to enroll in this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='watermarking_enabled',
            field=models.BooleanField(default=False, help_text='Visual watermarking for certificate fraud prevention'),
        ),
        migrations.AddField(
            model_name='organization',
            name='dpo_contact',
            field=models.EmailField(blank=True, help_text='DPO Contact Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='dpo_name',
            field=models.CharField(blank=True, help_text='Data Protection Officer Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='license_number',
            field=models.CharField(blank=True, help_text='E-Commerce / Training License Number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('DPA', 'Data Processing Agreement'), ('BREACH_PLAN', 'Breach Response Plan'), ('COOKIE_POLICY', 'Cookie Policy'), ('PRIVACY_POLICY', 'Privacy Policy'), ('T_AND_C', 'Terms & Conditions'), ('AUDIT_REPORT', 'Security Audit Report'), ('PEN_TEST', 'Penetration Test Report')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='compliance_docs/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='courses.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='regulatory_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.regulatoryauthority'),
        ),
        migrations.AddField(
            model_name='organization',
            name='regulatory_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.regulatoryauthority'),
        ),
    ]
