# Generated by Django 4.2.16 on 2026-05-05 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email'), ('chatbot', 'Chatbot'), ('telegram', 'Telegram')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='Phone number, email address, or URL', max_length=255)),
                ('business_hours', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['channel_type'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='encouragement_message',
            field=models.TextField(blank=True, default="Don't be discouraged — review the material and try again. You've got this!", help_text='Message shown to learners who fail an attempt'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_sla_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='course',
            name='job_opportunity',
            field=models.TextField(blank=True, help_text='Free-text job opportunity description', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='require_student_compliance',
            field=models.BooleanField(default=False, help_text='Block certificate until student compliance docs are approved'),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Headline salary range, e.g. $50k - $80k', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='accreditation_summary',
            field=models.TextField(blank=True, help_text='Public summary of credentials shown on profile'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin feedback / rejection reason'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='verification_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Requested')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Physical check-in for offline sessions', null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_by_instructor',
            field=models.BooleanField(default=False, help_text='True when an instructor manually marked attendance'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.livesession'),
        ),
        migrations.CreateModel(
            name='TrainerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('trade_license', 'Trade License'), ('vat_certificate', 'VAT Certificate'), ('accreditation', 'Accreditation Certificate'), ('id_proof', 'ID Proof'), ('cv', 'Curriculum Vitae'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='trainer_docs/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Requested'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Reviewer notes / rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.instructor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trainer_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='courses.instructor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(help_text='Phone, email, or external user id', max_length=200)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web Form'), ('email', 'Email'), ('chatbot', 'Chatbot')], default='web', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('passport', 'Passport'), ('emirates_id', 'Emirates ID'), ('photo', 'Photograph'), ('parental_consent', 'Parental Consent'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='student_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Requested')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_docs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('one_on_one', 'One-on-One')], default='offline', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical address (offline) or meeting link (online)', max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.instructor')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('region', models.CharField(blank=True, help_text='Region this salary range applies to', max_length=100)),
                ('courses', models.ManyToManyField(blank=True, related_name='job_roles', to='courses.course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.slot'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courses.slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
                'unique_together': {('slot', 'student')},
            },
        ),
    ]
