# Generated by Django 4.2.16 on 2026-05-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_supportchannel_assessment_encouragement_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='certificate_templates/')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='certificate_templates/previews/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default for new courses by this trainer')),
                ('notes', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='certificate_templates', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='courses.instructor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
