# Generated by Django 4.2.16 on 2026-05-22 18:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('attempt_number', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Total duration of attempt', null=True)),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('not_attempted', 'Not Attempted')], default='not_attempted', max_length=20)),
                ('success_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score_scaled', models.FloatField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, help_text='ISO 8601 total time', max_length=50)),
                ('session_id', models.CharField(help_text='Links to ScormTracking.session_id', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'SCORM Attempt',
                'verbose_name_plural': 'SCORM Attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScormModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('identifier', models.CharField(help_text='Unique identifier from manifest', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('launch', models.CharField(blank=True, help_text='Launch URL for this module (if directly launchable)', max_length=500, null=True)),
                ('resource_ref', models.CharField(blank=True, help_text='Reference to resource in manifest', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SCORM Module',
                'verbose_name_plural': 'SCORM Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='SCORM package title', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(choices=[('1.2', 'SCORM 1.2'), ('2004', 'SCORM 2004 4th Edition'), ('unknown', 'Unknown Version')], default='unknown', help_text='Detected SCORM version from manifest', max_length=10)),
                ('upload_file', models.FileField(help_text='Original .zip file', upload_to='scorm_packages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('entry_point', models.CharField(blank=True, help_text='Launch URL from imsmanifest.xml', max_length=500, null=True)),
                ('structure_tree', models.JSONField(default=dict, help_text='Hierarchical organization structure')),
                ('manifest_data', models.JSONField(default=dict, help_text='Parsed imsmanifest.xml content')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed', null=True)),
                ('processing_task_id', models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=100, null=True)),
                ('total_scos', models.IntegerField(default=0, help_text='Total SCOs (launchable units)')),
                ('total_modules', models.IntegerField(default=0, help_text='Total modules in organization')),
                ('language', models.CharField(default='en', help_text='Primary language of content', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_users', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SCORM Package',
                'verbose_name_plural': 'SCORM Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScormSco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('identifier', models.CharField(help_text='Unique identifier from manifest', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('launch_url', models.CharField(help_text='Relative path to launchable HTML/SCO', max_length=1000)),
                ('resource_type', models.CharField(default='webcontent', help_text='Type of resource (webcontent, asset, etc.)', max_length=50)),
                ('is_asset', models.BooleanField(default=False, help_text='True if asset (no API), False if SCO (uses API)')),
                ('max_time_allowed', models.DurationField(blank=True, help_text='Max time allowed to complete', null=True)),
                ('score_max', models.IntegerField(default=100, help_text='Maximum achievable score')),
                ('score_min', models.IntegerField(default=0, help_text='Minimum score')),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False, help_text='Must complete to finish module')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scos', to='scorm.scormmodule')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scos', to='scorm.scormpackage')),
            ],
            options={
                'verbose_name': 'SCORM SCO',
                'verbose_name_plural': 'SCORM SCOs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScormTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of learner', null=True)),
                ('lesson_status', models.CharField(choices=[('passed', 'Passed'), ('completed', 'Completed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('browsed', 'Browsed'), ('not attempted', 'Not Attempted')], default='not attempted', max_length=20)),
                ('entry_status', models.CharField(choices=[('ab-initio', 'First attempt'), ('resume', 'Resumed')], default='ab-initio', max_length=20)),
                ('score_raw', models.IntegerField(blank=True, help_text='Actual score achieved', null=True)),
                ('score_scaled', models.FloatField(blank=True, help_text='Normalized score (0-1)', null=True)),
                ('score_min', models.IntegerField(default=0)),
                ('score_max', models.IntegerField(default=100)),
                ('time_spent', models.DurationField(blank=True, help_text='Total time spent in ISO 8601 format', null=True)),
                ('first_access', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='When user marked as complete', null=True)),
                ('suspend_data', models.TextField(blank=True, help_text='Serialized state for resume (JSON)', null=True)),
                ('bookmark', models.CharField(blank=True, help_text='Lesson location/bookmark for resume', max_length=500, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('is_passed', models.BooleanField(default=False)),
                ('total_attempts', models.IntegerField(default=1)),
                ('launch_data', models.JSONField(default=dict, help_text='Initialization data passed to SCO')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorm.scormpackage')),
                ('sco', models.ForeignKey(blank=True, help_text='Current SCO being tracked', null=True, on_delete=django.db.models.deletion.CASCADE, to='scorm.scormsco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCORM Tracking',
                'verbose_name_plural': 'SCORM Tracking Records',
                'ordering': ['-last_access'],
            },
        ),
        migrations.CreateModel(
            name='ScormRuntimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('element', models.CharField(help_text="CMI element path (e.g., 'cmi.score.raw')", max_length=500)),
                ('value', models.TextField(help_text='Element value (can be JSON for complex types)')),
                ('commit_count', models.IntegerField(default=0, help_text='Number of commits for this element')),
                ('last_committed', models.DateTimeField(auto_now=True, help_text='Last time this element was committed')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_data', to='scorm.scormtracking')),
            ],
            options={
                'verbose_name': 'SCORM Runtime Data',
                'verbose_name_plural': 'SCORM Runtime Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['-created_at'], name='scorm_scorm_created_abbd14_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['status'], name='scorm_scorm_status_885f26_idx'),
        ),
        migrations.AddIndex(
            model_name='scormpackage',
            index=models.Index(fields=['version'], name='scorm_scorm_version_26fb66_idx'),
        ),
        migrations.AddField(
            model_name='scormmodule',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scorm.scormpackage'),
        ),
        migrations.AddField(
            model_name='scormmodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scorm.scormmodule'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorm.scormpackage'),
        ),
        migrations.AddField(
            model_name='scormattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scormtracking',
            index=models.Index(fields=['user', 'package'], name='scorm_scorm_user_id_88854a_idx'),
        ),
        migrations.AddIndex(
            model_name='scormtracking',
            index=models.Index(fields=['user', 'lesson_status'], name='scorm_scorm_user_id_8aed20_idx'),
        ),
        migrations.AddIndex(
            model_name='scormtracking',
            index=models.Index(fields=['session_id'], name='scorm_scorm_session_cdf999_idx'),
        ),
        migrations.AddIndex(
            model_name='scormtracking',
            index=models.Index(fields=['-last_access'], name='scorm_scorm_last_ac_2ee083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scormtracking',
            unique_together={('user', 'package', 'sco', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='scormsco',
            index=models.Index(fields=['package', 'module'], name='scorm_scorm_package_934029_idx'),
        ),
        migrations.AddIndex(
            model_name='scormsco',
            index=models.Index(fields=['module', 'order'], name='scorm_scorm_module__37f554_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scormsco',
            unique_together={('package', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='scormruntimedata',
            index=models.Index(fields=['tracking', 'element'], name='scorm_scorm_trackin_9be763_idx'),
        ),
        migrations.AddIndex(
            model_name='scormruntimedata',
            index=models.Index(fields=['tracking', '-updated_at'], name='scorm_scorm_trackin_005414_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scormruntimedata',
            unique_together={('tracking', 'element')},
        ),
        migrations.AddIndex(
            model_name='scormmodule',
            index=models.Index(fields=['package', 'parent'], name='scorm_scorm_package_955c47_idx'),
        ),
        migrations.AddIndex(
            model_name='scormmodule',
            index=models.Index(fields=['package', 'order'], name='scorm_scorm_package_2a18b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scormmodule',
            unique_together={('package', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['user', 'package'], name='scorm_scorm_user_id_d4323e_idx'),
        ),
        migrations.AddIndex(
            model_name='scormattempt',
            index=models.Index(fields=['session_id'], name='scorm_scorm_session_a01e44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scormattempt',
            unique_together={('user', 'package', 'attempt_number')},
        ),
    ]
